#!/usr/bin/env bash
#script taht creates a file, displays to infinity and beyond indefinitely
#diplays I hate the kill command when receiving a SIGTERM signal
#Deletes the file created and terminates itself  when receiving a SIGQUIT or SIGTERM signal



echo $$ >> /var/run/myscript.pid

function love() {
    rm /var/run/myscript.pid
    exit
}

trap "echo I hate the kill command;love" SIGTERM
trap "echo Y U no love me?!;love" SIGINT


while [ true ]; do
    echo To infinity and beyond;
done
